[package]
name = "halftone"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "halftone"
edition = "2018"
build = "src/build.rs"

[dependencies]
halftone-core = { path = "../src-core" }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tauri = { version = "0.11", features = [ "all-api" ] }

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[[bin]]
name = "halftone"
path = "src/main.rs"
