[package]
name = "halftone-core"
version = "0.0.1"
authors = [ "you" ]
edition = "2018"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
