name: Halftone CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone halftone repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: Set up halftone
        run: yarn install
      - run: |
          yarn run prettier:check
      - run: |
          yarn run eslint
      - run: |
          yarn run webpack:build
          ls -lAh ./dist
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          sudo apt update && \
          sudo apt install \
              libgtk-3-dev \
              libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              libssl-dev \
              appmenu-gtk3-module \
              squashfs-tools
      - run: |
          cargo fmt -- --check
      - run: |
          cargo install tauri-cli --version 1.0.0-beta-rc.2
      - run: |
          cargo tauri build
          ls -lAh ./target/release/bundle/deb/
      - run: |
          cargo clippy -- -D warnings
