name: Halftone CI

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: npm install
      - run: npm run prettier:check
      - run: npm run eslint
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo fmt -- --check
      - run: |
          cargo install tauri-bundler
      - run: |
          npm run tauri:build
          ls -lAh ./dist
          ls -lAh ./src-tauri/target/release/bundle/deb/
