name: Halftone CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone halftone repository
        uses: actions/checkout@v2
      - name: Clone tauri repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/tauri-apps/tauri
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: Set up halftone
        run: npm install
      - name: Set up tauri-cli
        run: |
          cd tauri/tooling/cli.js
          npm install
          npm run build
      - name: Set up tauri-api
        run: |
          cd tauri/tooling/api
          npm install
          npm run build
      - run: npm run prettier:check
      - run: npm run eslint
      - run: |
          npm run webpack:build
          ls -lAh ./dist
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          sudo apt update && \
          sudo apt install \
              libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              libssl-dev \
              appmenu-gtk3-module \
              libgtk-3-dev \
              squashfs-tools
      - run: |
          cargo fmt -- --check
      - run: |
          cargo install tauri-bundler
      - run: |
          npm run tauri:build
          ls -lAh ./target/release/bundle/deb/
      - run: |
          cargo clippy -- -D warnings
