name: Halftone CI

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - '*'
jobs:
  webpack-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: npm install
      - run: npm run prettier:check
      - run: npm run eslint
      - run: |
          npm run webpack:build
          ls -lAh ./dist
